### ISSUE TITLE
Wgnl_localizations license

### ISSUE THREAD

**Issue by ajvol** [wgnet/globalmap#1]
Could you authorize using translations under Creative Commons CC0? (so dual odbl & cc0 licensing)
Then I could load wgnl_localizations data into Wikidata.

**Comment by gnomeby** [comment]
Give us some time to find an answer with a legal department.

**Comment by gnomeby** [comment]
Good day.

Sorry for long time of waiting.
Our Legal Department has investigated the ODBL licence and found that it is only possible in case when we can get all OSM points additionally under CC0 licence. And accordingly to http://wiki.openstreetmap.org/wiki/Legal_FAQ (point 3f) it is hardly ever possible because OSM data is the collaborative work.

Have a good day.

**Comment by gnomeby** [comment]
Accordingly to licenses we can only export our translations to OSM back.
